### ISSUE TITLE
Hyprland-custom file doesnt exist.

### ISSUE THREAD

**Issue by ghostranger047** [khaneliman/dotfiles#12]
In hyprland manual installation there is a command to symlink ~/.local/bin/Hyprland-custom.
But the file seems to be missing in your dot files.
Need some help.

**Comment by khaneliman** [comment]
> In hyprland manual installation there is a command to symlink ~/.local/bin/Hyprland-custom.
> 
> But the file seems to be missing in your dot files.
> 
> Need some help.

Sorry, I forgot to update the readme. In the new version of hyprland they support a new environment variable syntax that removes the need for the custom launcher. I'll update the readme shortly but you don't need to create those symlinks for the hyprland desktop, custom, and wlroots files. The environment.conf file will handle what those files did.

**Comment by ghostranger047** [comment]
I think u sd also update your:
`dots/linux/hyprland/usr/share/wayland-sessions/hyprland-custom.desktop`
And also the auto install script.

**Comment by ghostranger047** [comment]
Also it would be great if u list out all the dependencies including the fonts used.

**Comment by khaneliman** [comment]
> I think u sd also update your: `dots/linux/hyprland/usr/share/wayland-sessions/hyprland-custom.desktop` And also the auto install script.

Script was updated and that was just a missed file to remove. 

> Also it would be great if u list out all the dependencies including the fonts used.

Yeah, i can try and append the application dependencies. But, the fonts are included in the dots.

**Comment by ghostranger047** [comment]
Its is worth mentioning that you did the dual monitor setup very well .....
But i have a single monitor HDMI-A-1 with a resolution 1920x1080. I managed to fix waybar by changing all DP-1 to HDMI-A-1.
BUT still i am not getting the workspace icons.
Is there an easy way to convert to single monitor setup?

**Comment by khaneliman** [comment]
> Its is worth mentioning that you did the dual monitor setup very well ..... But i have a single monitor HDMI-A-1 with a resolution 1920x1080. I managed to fix waybar by changing all DP-1 to HDMI-A-1. BUT still i am not getting the workspace icons. Is there an easy way to convert to single monitor setup?

If the workspace section is functioning, but you are not seeing the icons. I'd double check if you installed the font from shared. https://github.com/khaneliman/dotfiles/tree/main/dots/shared/home/.fonts/SanFransisco/SF-Ligaturized

`font-family: Liga SFMono Nerd Font;`

**Comment by khaneliman** [comment]
> Is there an easy way to convert to single monitor setup?

The waybar/config.jsonc is an array of items. The primary monitor is DP-2 so if you replaced DP-1 you're getting the second monitor experience. You can just rip out the secondary monitor object in that array. I'm not sure how well the stats and tray will fit in the smaller monitor, you might have adjust styling a bit though. 

```jsonc
[
  {
    "include": [
      "~/.config/waybar/default-modules.jsonc"
    ],
    "layer": "top",
    "position": "top",
    "output": "HDMI-A-1",
    "margin-top": 10,
    "margin-left": 20,
    "margin-right": 20,
    "modules-center": [],
    "modules-left": [
      "custom/wlogout",
      "wlr/workspaces",
      "custom/separator-left",
      "hyprland/window"
    ],
    "modules-right": [
      "tray",
      "custom/separator-right",
      "group/stats",
      "custom/separator-right",
      "group/notifications",
      "hyprland/submap",
      "custom/weather",
      "clock"
    ]
  }
]
```
